import json
import os
import re
import unicodedata

# Valid categories defined in generator_v2.py
VALID_CATEGORIES = {
    "concrete_nouns",
    "abstract_nouns",
    "action_verbs",
    "adjectives_states",
    "adverbs_functional"
}

def clean_filename_korean(korean):
    # Strips all potential file-system hostile characters
    cleaned = re.sub(r'[\s/,;\?:\*\"<>\|\\\.\(\)\[\]\{\}]', '', korean)
    return unicodedata.normalize('NFC', cleaned)

def clean_filename_japanese(jp):
    # Strips spaces and hostile characters in Japanese representation
    cleaned = jp.replace(' ', '')
    cleaned = re.sub(r'[\s/,;\?:\*\"<>\|\\\.\(\)\[\]\{\}〜~]', '', cleaned)
    return unicodedata.normalize('NFC', cleaned)

def check_vocab():
    path = "utils/image_pipeline_v2/word_categories_all.json"
    if not os.path.exists(path):
        print(f"❌ Error: {path} not found.")
        return

    with open(path, 'r', encoding='utf-8') as f:
        categories = json.load(f)

    print("📊 Loaded word categories. Starting DEEP validation...")
    
    total_words = 0
    errors = []
    warnings = []
    nfd_count = 0
    
    seen_ids = {}
    seen_filenames = {}
    
    for cat, words in categories.items():
        # Check 1: Category Name Check
        if cat not in VALID_CATEGORIES:
            errors.append(f"❌ Invalid Category Key in JSON: '{cat}' (Not supported by PROMPT_TEMPLATES)")
            continue
            
        for i, w in enumerate(words):
            total_words += 1
            w_id = w.get('id')
            kanji = w.get('kanji', '')
            hiragana = w.get('hiragana', '')
            korean = w.get('korean', '')
            english = w.get('english', '')
            example_jp = w.get('exampleJp', '')
            example_ko = w.get('exampleKo', '')
            
            # Check 2: ID check
            if not w_id:
                errors.append(f"[{cat} @ Index {i}] Missing ID")
                continue
            
            # Check 3: Duplicate ID
            if w_id in seen_ids:
                errors.append(f"❌ Duplicate ID: '{w_id}' (Found in category '{cat}' and '{seen_ids[w_id]}')")
            seen_ids[w_id] = cat
                
            # Check 4: Korean and English missing check
            if not korean:
                errors.append(f"[{w_id}] Missing Korean translation (Cannot generate image name)")
            if not english:
                warnings.append(f"[{w_id}] Missing English translation (Gemini prompt will fallback to Korean: '{korean}')")
                
            # Check 5: Japanese text check
            if not kanji and not hiragana:
                errors.append(f"[{w_id}] Both kanji and hiragana fields are empty")
                
            # Check 6: Example pair mismatch
            if (example_jp and not example_ko) or (example_ko and not example_jp):
                errors.append(f"[{w_id}] Example sentence pair mismatch (JP={bool(example_jp)}, KO={bool(example_ko)})")
                
            # Check 7: Deep filename collision & Sanitization dry-run
            if korean and (kanji or hiragana):
                level = w.get('level') or 'n4'
                japanese = clean_filename_japanese(kanji or hiragana)
                safe_kor = clean_filename_korean(korean)
                
                # Check for empty string after sanitization
                if not japanese:
                    errors.append(f"[{w_id}] Japanese representation became EMPTY after sanitization: '{kanji or hiragana}'")
                if not safe_kor:
                    errors.append(f"[{w_id}] Korean translation became EMPTY after sanitization: '{korean}'")
                
                filename = f"{level}_{japanese}_{safe_kor}.jpg"
                
                if filename in seen_filenames:
                    errors.append(f"🚨 Filename collision: '{filename}' generated by both {w_id} and {seen_filenames[filename]}")
                seen_filenames[filename] = w_id
                
            # Check 8: Check NFD encoding in all text fields
            for field_name, val in [('korean', korean), ('exampleKo', example_ko), ('kanji', kanji), ('hiragana', hiragana), ('english', english)]:
                if val:
                    normalized = unicodedata.normalize('NFC', val)
                    if normalized != val:
                        nfd_count += 1
                        w[field_name] = normalized

    print(f"\n✅ Deep Scan Finished.")
    print(f"  - Total words scanned: {total_words}")
    print(f"  - Total critical errors & collisions: {len(errors)}")
    print(f"  - Total warnings (missing fields / fallbacks): {len(warnings)}")
    print(f"  - Total NFD (decomposed Hangul/Kana) fields detected: {nfd_count}")
    
    if errors:
        print("\n❌ Critical Errors & Collisions List:")
        for err in errors[:30]:
            print(f"  * {err}")
        if len(errors) > 30:
            print(f"  * ... and {len(errors)-30} more errors.")
            
    if warnings:
        print("\n⚠️ Warnings List:")
        for warn in warnings[:10]:
            print(f"  * {warn}")
        if len(warnings) > 10:
            print(f"  * ... and {len(warnings)-10} more warnings.")

    # Save NFC normalization back if NFD was detected
    if nfd_count > 0:
        print("\n✏️ Automatically correcting NFD back to NFC...")
        with open(path, 'w', encoding='utf-8') as f:
            json.dump(categories, f, ensure_ascii=False, indent=2)
        print("💾 Normalization fix saved successfully.")

if __name__ == "__main__":
    check_vocab()


